version: "3"
services:
  api:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    ports:
      - "5000:5000"
    container_name: yugioh-pairings-system-api
    volumes:
      - .:/yugioh-swiss-pairings-api